#!/usr/bin/env python3
"""
Parametric blockMeshDict generator for the square-section 180-deg U-duct.

Geometry (nondimensional, D=1), matches Cheah et al. 1996 / 2021 ST-VMS paper:
  - square DxD cross-section
  - 180-deg bend, mean radius Rc/D = 0.65 (inner Ri=0.15, outer Ro=1.15)
  - inlet leg Lin = 3D, outlet leg Lout = 6.5D
Bend plane = x-y; spanwise = z (width D). Bend centre O=(0,0) at the bottom.
Left leg (inlet, flow -y) at x=-Rc; right leg (outlet, flow +y) at x=+Rc.

Topology: 4 hex blocks sharing faces
  A  inlet leg      (straight, along y)
  B1 bend 180->270  (annular sector, arc edges)
  B2 bend 270->360  (annular sector, arc edges)
  C  outlet leg     (straight, along y)

Usage: python3 genUduct.py [level] > system/blockMeshDict   # level in {A,B,C,D,E}; default C

Levels B, C and D are the coarse, medium and fine meshes of the accompanying study
(467,712, 1,105,920 and 2,927,232 cells).
"""
import sys, math

# --- parameters ---
D   = 1.0
Ri  = 0.15
Ro  = 1.15
Lin = 3.0
Lout= 6.5

# cross-section (radial + spanwise) grading: each half graded towards its wall with an
# expansion ratio of 500 (first cell ~1.8e-4 D on level C, y+ < 2 at Re = 1e5).
GR_RANS = "( (0.5 0.5 500) (0.5 0.5 0.002) )"

# refinement levels: (ns radial, nspan, cells-per-D streamwise, cells per 90deg)
LEVELS = {
    "A": dict(ns=32, nspan=32, cpd=10, nb90=20),
    "B": dict(ns=48, nspan=48, cpd=15, nb90=30),
    "C": dict(ns=64, nspan=64, cpd=20, nb90=40),   # medium (default)
    "D": dict(ns=88, nspan=88, cpd=28, nb90=56),
    "E": dict(ns=120,nspan=120,cpd=38, nb90=76),
}
lvl = sys.argv[1] if len(sys.argv) > 1 else "C"
P = LEVELS[lvl]
ns, nspan = P["ns"], P["nspan"]
nin  = int(round(P["cpd"]*Lin))
nout = int(round(P["cpd"]*Lout))
nb90 = P["nb90"]

GR = P.get("gr", GR_RANS)

# streamwise leg grading: FINE at the bend junction (matches bend cell size, resolves
# the inner-wall separation/recovery), expanding toward the far field. Value = last/first
# cell ratio along local y (bend -> far end). Inlet coarsens more (flow fully-developed);
# outlet kept moderate to resolve downstream stations (Cheah x/D up to 6).
EXP_IN  = P.get("exp_in", 8.0)
EXP_OUT = P.get("exp_out", 5.0)

# --- 2D points (x,y) at z=0; z=1 layer = index + 10 ---
pts2d = [
    (-Ro,  Lin),   # 0  A top outer
    (-Ri,  Lin),   # 1  A top inner
    (-Ri,  0.0),   # 2  theta180 inner (A/B1 shared)
    (-Ro,  0.0),   # 3  theta180 outer
    ( 0.0,-Ri),    # 4  theta270 inner (B1/B2 shared)
    ( 0.0,-Ro),    # 5  theta270 outer
    ( Ri,  0.0),   # 6  theta360 inner (B2/C shared)
    ( Ro,  0.0),   # 7  theta360 outer
    ( Ri,  Lout),  # 8  C top inner
    ( Ro,  Lout),  # 9  C top outer
]
N = len(pts2d)

def verts():
    out = []
    for z in (0.0, 1.0):
        for (x, y) in pts2d:
            out.append((x, y, z))
    return out

# --- arc edge midpoints ---
def polar(r, deg):
    a = math.radians(deg)
    return (r*math.cos(a), r*math.sin(a))
mo225 = polar(Ro, 225); mi225 = polar(Ri, 225)
mo315 = polar(Ro, 315); mi315 = polar(Ri, 315)

def fmt(v): return f"({v[0]:.8g} {v[1]:.8g} {v[2]:.8g})"

# --- blocks: (v0..v7), (n1 n2 n3), grading(x,y,z) ---
# local x=radial(outer->inner)=ns; local y=streamwise; local z=span=nspan
# NOTE: bottom faces (first 4 verts) MUST wind CCW viewed from +z (positive volume);
# top face (last 4) = same order + N(=10). local x=radial, y=streamwise/bend, z=span.
# yg = local-y (streamwise/bend) expansion ratio; local y runs bend -> far end for legs.
blocks = [
    # A inlet leg   (fine at bend, coarser toward inlet)
    ((3,2,1,0, 13,12,11,10), (ns,nin,nspan),   EXP_IN),
    # B1 bend 180->270  (uniform along arc)
    ((2,3,5,4, 12,13,15,14), (ns,nb90,nspan),  1.0),
    # B2 bend 270->360  (uniform along arc)
    ((4,5,7,6, 14,15,17,16), (ns,nb90,nspan),  1.0),
    # C outlet leg  (fine at bend, moderate coarsening toward outlet)
    ((6,7,9,8, 16,17,19,18), (ns,nout,nspan),  EXP_OUT),
]

# --- arc edges (both z layers) ---
arcs = [
    (3,5, mo225), (13,15, mo225),   # B1 outer
    (2,4, mi225), (12,14, mi225),   # B1 inner
    (5,7, mo315), (15,17, mo315),   # B2 outer
    (4,6, mi315), (14,16, mi315),   # B2 inner
]

# --- boundary faces ---
inlet  = [(0,1,11,10)]
outlet = [(8,9,19,18)]
walls  = [
    # spanwise z=0 faces
    (3,2,1,0),(3,2,4,5),(5,4,6,7),(7,6,8,9),
    # spanwise z=1 faces
    (13,12,11,10),(13,12,14,15),(15,14,16,17),(17,16,18,19),
    # outer radial walls
    (3,0,10,13),(3,5,15,13),(5,7,17,15),(7,9,19,17),
    # inner radial walls
    (2,1,11,12),(2,4,14,12),(4,6,16,14),(6,8,18,16),
]

# --- emit ---
def emit():
    L = []
    L.append("/*--- U-duct blockMeshDict (generated by genUduct.py, level %s) ---*/" % lvl)
    L.append("FoamFile { version 2.0; format ascii; class dictionary; object blockMeshDict; }")
    L.append("scale 1;\n")
    L.append("vertices\n(")
    for i, v in enumerate(verts()):
        L.append(f"    {fmt(v)}   // {i}")
    L.append(");\n")
    L.append("blocks\n(")
    for (vv, nn, yg) in blocks:
        vs = " ".join(str(x) for x in vv)
        L.append(f"    hex ({vs}) ({nn[0]} {nn[1]} {nn[2]}) simpleGrading ( {GR} {yg:g} {GR} )")
    L.append(");\n")
    L.append("edges\n(")
    for (a, b, m) in arcs:
        L.append(f"    arc {a} {b} ({m[0]:.8g} {m[1]:.8g} {'0' if a<10 else '1'})")
    L.append(");\n")
    L.append("boundary\n(")
    L.append("    inlet { type patch; faces ( %s ); }" % " ".join("(%d %d %d %d)"%f for f in inlet))
    L.append("    outlet { type patch; faces ( %s ); }" % " ".join("(%d %d %d %d)"%f for f in outlet))
    L.append("    walls { type wall; faces\n        (")
    for f in walls:
        L.append("            (%d %d %d %d)" % f)
    L.append("        );\n    }")
    L.append(");\n")
    L.append("mergePatchPairs ();")
    return "\n".join(L)

if __name__ == "__main__":
    ncell = ns*nin*nspan + 2*ns*nb90*nspan + ns*nout*nspan
    sys.stderr.write(f"[genUduct] level {lvl}: ns={ns} nspan={nspan} nin={nin} nout={nout} "
                     f"nb90={nb90}  ~{ncell:,} cells\n")
    print(emit())
